// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGiim3UDIQp7ACL_DFG82k1CnSNZuvoDg',
    appId: '1:696567663861:web:106dcf896badc46aad89bc',
    messagingSenderId: '696567663861',
    projectId: 'medilink-8b42a',
    authDomain: 'medilink-8b42a.firebaseapp.com',
    storageBucket: 'medilink-8b42a.firebasestorage.app',
    measurementId: 'G-K69N2TWDNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlsRVihI233DO3gpdpowMVOKnq-wJKwO4',
    appId: '1:696567663861:android:34df08bf5971c526ad89bc',
    messagingSenderId: '696567663861',
    projectId: 'medilink-8b42a',
    storageBucket: 'medilink-8b42a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1B8u1XHCqRazhNe-pfi0se9fp905KsuI',
    appId: '1:696567663861:ios:2d10c4c22378c36bad89bc',
    messagingSenderId: '696567663861',
    projectId: 'medilink-8b42a',
    storageBucket: 'medilink-8b42a.firebasestorage.app',
    iosBundleId: 'com.example.healthymamaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1B8u1XHCqRazhNe-pfi0se9fp905KsuI',
    appId: '1:696567663861:ios:2d10c4c22378c36bad89bc',
    messagingSenderId: '696567663861',
    projectId: 'medilink-8b42a',
    storageBucket: 'medilink-8b42a.firebasestorage.app',
    iosBundleId: 'com.example.healthymamaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGiim3UDIQp7ACL_DFG82k1CnSNZuvoDg',
    appId: '1:696567663861:web:5d0716e6cd33ce8ead89bc',
    messagingSenderId: '696567663861',
    projectId: 'medilink-8b42a',
    authDomain: 'medilink-8b42a.firebaseapp.com',
    storageBucket: 'medilink-8b42a.firebasestorage.app',
    measurementId: 'G-HZ90MYYEQT',
  );
}
